// src/shopping/Shopping.svelte
<script lang="ts">
    import { recipesList, productsList, removeRecipeFromList, addRecipeToList, checkProduct, uncheckProduct } from "../data/data.exports";
    import type { ProductsListItem, RecipesListItem } from "../data/data.service";

    $: selectedRecipes = $recipesList.filter((r) => r.count > 0);
    $: neededProductsList = $productsList.filter((p) => p.amount > 0);

    function onMinusClick(r: RecipesListItem) {
        removeRecipeFromList(r.recipe);
    }

    function onPlusClick(r: RecipesListItem) {
        addRecipeToList(r.recipe);
    }

    function onProductChecked(product: ProductsListItem, event: any) {
        if(event.target.checked) {
            checkProduct(product);
        } else {
            uncheckProduct(product);
        }
    }
</script>

<h1>Meals:</h1>
<ul>
    {#each selectedRecipes as r}
    <li>
        <span>{r.recipe.title}</span>
        <button on:click={() => onMinusClick(r)}>-</button>
        <span>{r.count}</span>
        <button on:click={() => onPlusClick(r)}>+</button>
    </li>
    {/each}
</ul>
<h1>Products:</h1>
<ul>
    {#each neededProductsList as p}
    <li class:checked={p.checked}>
        <span>{p.product.name}</span>
        <span>{p.amount}</span>
        <input type="checkbox" checked={p.checked} on:change={(e) => onProductChecked(p, e)}>
    </li>
    {/each}
</ul>


<style>
    .checked {
        text-decoration: line-through;
    }

    button {
        height: 32px;
        width: 32px;
        background-color: white;
        border: solid 1px lightgray;
        border-radius: 16px;
    }
</style>

// src/app/shopping/shopping.component.ts
import { Component } from '@angular/core';
import {
  DataService,
  ProductsListItem,
  RecipesListItem,
} from '../data/data.service';
import { Recipe } from '../models/recipe.model';

@Component({
  selector: 'shopping',
  templateUrl: './shopping.component.html',
  styleUrls: ['./shopping.component.css'],
})
export class ShoppingComponent {
  get selectedRecipes(): RecipesListItem[] {
    return this.dataService.recipesList.filter((r) => r.count > 0);
  }

  get productsList(): ProductsListItem[] {
    return this.dataService.productsList.filter((p) => p.amount > 0);
  }

  constructor(private dataService: DataService) {}

  onAddRecipeClick(recipe: Recipe): void {
    this.dataService.addRecipeToList(recipe);
  }

  onRemoveRecipeClick(recipe: Recipe): void {
    this.dataService.removeRecipeFromList(recipe);
  }

  onProductChecked(p: ProductsListItem, event: any): void {
    if (event.checked) {
      this.dataService.checkProduct(p.product);
    } else {
      this.dataService.uncheckProduct(p.product);
    }
  }
}

<mat-list>
  <div mat-subheader>Meals</div>
  <mat-list-item *ngFor="let item of selectedRecipes">
    <mat-icon mat-list-icon>restaurant</mat-icon>
    <div>{{ item.recipe.title }}</div>
    <button mat-flat-button (click)="onRemoveRecipeClick(item.recipe)">
      <mat-icon mat-list-icon>remove</mat-icon>
    </button>
    <span>{{ item.count }}</span>
    <button mat-flat-button (click)="onAddRecipeClick(item.recipe)">
      <mat-icon mat-list-icon>add</mat-icon>
    </button>
  </mat-list-item>
  <mat-divider></mat-divider>
  <div mat-subheader>Products</div>
  <mat-list-item
    *ngFor="let p of productsList"
    class="product-list-item"
    [ngClass]="{ checked: p.checked }"
  >
    <div mat-line>{{ p.product.name }}</div>
    <mat-checkbox [ngModel]="p.checked" (change)="onProductChecked(p, $event)">
    </mat-checkbox>
    <div *ngIf="p.amount > 0" mat-line>{{ p.amount }}</div>
  </mat-list-item>
</mat-list>
